/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AltRouteImport } from './routes/alt'
import { Route as IndexRouteImport } from './routes/index'

const AltRoute = AltRouteImport.update({
  id: '/alt',
  path: '/alt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alt': typeof AltRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alt': typeof AltRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alt': typeof AltRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alt'
  id: '__root__' | '/' | '/alt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AltRoute: typeof AltRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/alt': {
      id: '/alt'
      path: '/alt'
      fullPath: '/alt'
      preLoaderRoute: typeof AltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AltRoute: AltRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
